// <auto-generated />
using System;
using ControleDeProjetosProauto.Setup.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleDeProjetosProauto.Migrations
{
    [DbContext(typeof(ControleContext))]
    partial class ControleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ControleDeProjetosProauto.Models.Projetos", b =>
                {
                    b.Property<int>("PRONID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("PROCSTAT")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PRODDATCAD")
                        .HasColumnType("TEXT");

                    b.Property<string>("PROSDESPRO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PROSNPRO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PROSOBRIG")
                        .HasColumnType("TEXT");

                    b.HasKey("PRONID");

                    b.ToTable("projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
